### ISSUE TITLE
API discussion

### ISSUE THREAD

**Issue by cudr** [cudr/slate-collaborative#5]
Welcome any ideas about plugin and microservice API

**Comment by simpleshadow** [comment]
Big thanks for your work, @cudr! 

Do you have suggestions for what should be worked on next?

I noticed the following issues:

- Block (node) `type` operations are not being set.
- The cursor on occasion will move on its own to the right.
- Data can get out of sync but I believe this is due to disconnects and persistence being in memory (not database)

**Comment by cudr** [comment]
@simpleshadow, thanks for your feedback!

Need steps to reproduce it to fix.

Can you describe more details this issues or attach link repro (e.g. codesandbox)?

**Comment by cudr** [comment]
Regarding the fourth point, I created a issue: https://github.com/ianstormtaylor/slate/issues/3063, but did'n receive any feedback
