### ISSUE TITLE
How to just use the offline version of the AutoMerge and SlateJs 

### ISSUE THREAD

**Issue by trannhutle** [cudr/slate-collaborative#51]
Hi @cudr

I am very appreciate your work about this project.

We are currently using SlateJS 0.47.9 in JS.

If we would like to use your plugin how could I do it?

Do you know what is the implementation which is just to compare the Slate json object by using Automerge offline.

Thank you very much.

**Comment by cudr** [comment]
Hi @trannhutle!

You can try using slate-sollaborative v0.0.3, but I strongly discourage doing this because it is outdated. Important note that older versions of slatejs have been deprecated, the slatejs api has been changed, and the slate-collaborative api has also been changed. You can check this in the commit history.
